django-project/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("counter/", include("counter.urls")),
]

django-project/counter/urls.py
# counter/urls.py
from django.urls import path

from . import views

app_name = "counter"
urlpatterns = [
    path("", views.index, name="index"),
    path('<int:counter_id>', views.counter_log, name='counter-log'),
    path("new-counter", views.new_counter, name="new-counter"),
]

django-project/counter/models.py
from django.db import models
from django.urls import reverse

class BaseTimestamp(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class CountProcess(BaseTimestamp):
    max_count = models.IntegerField()
    current_count = models.IntegerField(default=0)

    def is_complete(self):
        return self.current_count == self.max_count
    
    def __str__(self):
        return f"Count Process #{self.id}"

    def get_absolute_url(self):
        return reverse("counter:counter-log", args=[self.id])

    def get_websocket_url(self):
        return f"/ws{self.get_absolute_url()}/"

django-project/counter/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_protect

import json
from .models import CountProcess

@csrf_protect
def index(request):
    return render(request, "counter/index.html")

def new_counter(request):
    if request.method == 'POST':
        request_body = json.loads(request.body)
        max_count = int(request_body['max_count'])
        counter = CountProcess.objects.create(max_count=max_count)

        data = {
            "counter_url": counter.get_absolute_url()
        }
        return JsonResponse(data=data)
    else:
        return render(request, "counter/index.html")

def counter_log(request, counter_id):
    counter = CountProcess.objects.get(id=counter_id)
    context = {
        "counter": counter
    }
    return render(request, 'counter/counter.html', context=context)

django-project/templates/counter/counter.html
<!-- templates/counter/counter.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Number Counter</title>
</head>
<body>
    <h1>{{ counter }}</h1>
    <p>Counting to {{counter.max_count}}</p>
    <textarea id="count-log" cols="100" rows="20"></textarea><br>
    <input id="start-count-submit" type="button" value="Start">
    <input id="pause-count-submit" type="button" value="Pause" disabled>

    <script>
        const countLogger = document.querySelector('#count-log');
        const startButton = document.querySelector('#start-count-submit');
        const pauseButton = document.querySelector('#pause-count-submit');
        
        // Pre-populate logger
        countLogger.value = "";
        let currentCount = parseInt("{{counter.current_count}}");
        for(let i = 0; i <= currentCount; i++) {
            countLogger.value += ("Step " + i + "\n");
        }

        // Websocket Functions
        const counterSocket = new WebSocket(
            'ws://'
            + window.location.host
            + "{{ counter.get_websocket_url }}"
        )

        counterSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);

            switch (data.type) {
                case "start_ack":
                    startButton.setAttribute('disabled', 'true');
                    pauseButton.removeAttribute('disabled');
                    break;
                case "pause_ack":
                    pauseButton.setAttribute('disabled', 'true');
                    startButton.removeAttribute('disabled');
                    break;
            }
            countLogger.value += (data.message + "\n");
        }

        counterSocket.onclose = function(e) {
            console.error('Counter socket closed unexpectedly');
            countLogger.value += ('socket closed\n');
        }

        // Button Functions
        startButton.onclick = function(e) {
            // Flag counter start
            counterSocket.send(JSON.stringify({
                "type": "start",
            }));
        }

        pauseButton.onclick = function(e) {
            // Pause counter
            counterSocket.send(JSON.stringify({
                "type": "pause",
            }));
        }
    </script>
</body>
</html>

django-project/templates/counter/index.html
<!-- templates/logger/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Number Counter</title>
</head>
<body>
    What should I count to?<br>
    <form method="post">{% csrf_token %}</form>
    <input id="counter-max-input" type="number" min="1" max="300" size="100"><br>
    <input id="counter-max-submit" type="button" value="New Counter">

    <script>
        // Get CSRF Token
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');

        document.querySelector('#counter-max-input').focus();
        document.querySelector('#counter-max-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#counter-max-submit').click();
            }
        };

        document.querySelector('#counter-max-submit').onclick = async function(e) {
            let maxCount = document.querySelector('#counter-max-input').value;
            if (maxCount < 1 || maxCount > 300) {
                alert("Invalid count value!!!");
                return;
            }
            let data = {
                'max_count': maxCount,
            }
            let response = await fetch("{% url 'counter:new-counter' %}", {
                method: 'POST',
                headers: {'X-CSRFToken': csrftoken},
                body: JSON.stringify(data),
            });
            let response_data = await response.json();
            window.location.pathname = response_data.counter_url;
        };
    </script>
</body>
</html>